name: review artifact

on:
  workflow_dispatch:
     
    inputs:
      name:
        description: 'Choose artifact'
        default: 'python'
        required: true
        type: choice
        options: 
          - python
          - java

jobs:

  review:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/download-artifact@v4
      with:
        path: my-artifact
    - name: Display structure of downloaded files
      run: ls -R my-artifact
