name: review artifact

on:
  workflow_dispatch:
     
    inputs:
      name:
        description: 'Choose artifact'
        default: 'python'
        required: true
        type: choice
        options: 
          - python
          - java

jobs:

  review:
    runs-on: ubuntu-latest

    steps:
    - name: Sign in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: ghcr.io
    - name: Display structure of downloaded files
      run: |
        ls -la
        docker pull ghcr.io/innotech-devops-teralco/repo_jorgeivan/python:1.0.0
        
