name: Hello World Training Workflow

on:
  workflow_dispatch:
jobs:
  use_api:
    runs-on: ubuntu-latest
    permissions:
      issues: read
      packages: read
    steps:
      - env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh api  /repos/innotech-devops-teralco/repo_jorgeivan/actions/artifacts
